generic:
  function: generic/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
publish-events:
  function: publish-events/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    apiKey: $SERVICE_API_KEY
  annotations:
    require-adobe-auth: true
    final: true
