bearer-token-action:
  function: bearer-token-action/index.js
  web: 'yes'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
commerce-basic-action:
  function: commerce-basic-action/index.js
  web: 'yes'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
    PAAS_BASE_URL: $PAAS_BASE_URL
    AUTH_USERNAME: $AUTH_USERNAME
    AUTH_PASSWORD: $AUTH_PASSWORD
  annotations:
    require-adobe-auth: true
    final: true
commerce-ims-action:
  function: commerce-ims-action/index.js
  web: 'yes'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
    SAAS_BASE_URL: $SAAS_BASE_URL
    OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
    OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
    OAUTH_TECHNICAL_ACCOUNT_ID: $OAUTH_TECHNICAL_ACCOUNT_ID
    OAUTH_TECHNICAL_ACCOUNT_EMAIL: $OAUTH_TECHNICAL_ACCOUNT_EMAIL
    OAUTH_ORG_ID: $OAUTH_ORG_ID
    OAUTH_SCOPES: $OAUTH_SCOPES
  annotations:
    require-adobe-auth: true
    final: true
commerce-oauth-action:
  function: commerce-oauth-action/index.js
  web: 'yes'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
    PAAS_BASE_URL: $PAAS_BASE_URL
    OAUTH_CONSUMER_KEY: $OAUTH_CONSUMER_KEY
    OAUTH_CONSUMER_SECRET: $OAUTH_CONSUMER_SECRET
    OAUTH_ACCESS_TOKEN: $OAUTH_ACCESS_TOKEN
    OAUTH_ACCESS_TOKEN_SECRET: $OAUTH_ACCESS_TOKEN_SECRET
  annotations:
    require-adobe-auth: true
    final: true
graphql-action:
  function: graphql-action/index.js
  web: 'yes'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
rest-client-action:
  function: rest-client-action/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
runtime-action:
  function: runtime-action/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
